version: '2'
services:
  database:
    image: 'mysql:5.7'
    ports:
      - '3301:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: 'redis:3.0'
    ports:
      - '6371:6379'

  web: &base
    build:
      context: .
    volumes:
      - .:/var/app
    ports:
      - '3001:3000'
    links:
      - database
      - redis
    environment:
      REDIS_HOST: redis
      WEATHER_API_URL: api.openweathermap.org/data/2.5/weather?
      APIID: 91717eb549780bd9fe1d11fe52a409b3
